# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipstercookbookapp
services:
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  redis:
    extends:
      file: ./redis.yml
      service: redis
